name: Java CI

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml
      continue-on-error: true
      
    - name: Test with Maven
      run: mvn -B test --file pom.xml
      id: tests
      continue-on-error: true
      
    - name: Telegram Notify
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
            GitHub Actions Notification:
            - Event: ${{ github.event_name }}
            - Repository: ${{ github.repository }}
            - Workflow: ${{ github.workflow }}
            - Action Status: ${{ job.status }}
            - Tests: ${{ steps.tests.outcome }}
