name: Java CI

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: maven

    - name: Run Tests
      run: mvn test -Dsurefire.reportFormat=xml -Dmaven.test.failure.ignore=true

    - name: Check Test Results
      id: check
      run: |
        if grep -q '<failure' **/target/surefire-reports/*.xml; then
          echo "::set-output name=status::FAIL"
          failures=$(grep -oPm1 "(?<=<failure.*>).*(?=</failure>)" **/target/surefire-reports/*.xml)
          echo "::set-output name=details::${failures}"
        else
          echo "::set-output name=status::OK"
        fi

    - name: Telegram Notify on Test Success
      if: steps.check.outputs.status == 'OK'
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: "Всё ок!"

    - name: Telegram Notify on Test Failure
      if: steps.check.outputs.status == 'FAIL'
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: "Что-то упало: ${{ steps.check.outputs.details }}"
